/**
 * Patch native-module gyp files so they compile for Electron on Windows under
 * two conditions the stock sources don't survive:
 *
 *  1. Repo path contains a space (node-gyp #65). node-pty's
 *     `deps/winpty/src/winpty.gyp` runs two `cmd /c "cd shared && <bat>"` gyp
 *     actions that break under a spaced project path. Remove both shell-outs:
 *     hardcode `WINPTY_COMMIT_HASH` to "none" (diagnostics-only string baked
 *     into the binary), replace the `UpdateGenVersion.bat` include-dir action
 *     with a literal `'gen'`, and pre-generate `gen/GenVersion.h`.
 *
 *  2. VS Build Tools without the Spectre-mitigated libraries component. Several
 *     native addons set `SpectreMitigation: 'Spectre'` on their targets, which
 *     makes MSBuild require the Spectre libs (MSB8040) — observed on node-pty
 *     and native-keymap. These addons don't need Spectre hardening to function,
 *     so do a GENERAL pass over every `.gyp` in the bun store and disable it.
 *     This catches current and future compiling modules in one shot instead of
 *     per-module whack-a-mole.
 *
 * These addons have no Electron-ABI prebuilt, so @electron/rebuild must compile
 * them from source. Idempotent; win32-only. Run by postinstall.ts before
 * `install:deps` (electron-builder install-app-deps).
 */
import {
	existsSync,
	globSync,
	mkdirSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";

// native-keymap@3.3.9 (the latest) calls the old no-tag V8
// `GetAlignedPointerFromInternalField()`, deprecated in Electron 40's V8
// (C4996). The API still works at runtime — it's deprecated, not removed — but
// the deprecation is fatal at compile time. Inject `/wd4996` into native-keymap's
// MSVC flags to suppress it. Anchored on `/ZH:SHA_256` (a Microsoft security
// flag that's the last entry in its AdditionalOptions array) so the injection is
// deterministic; `/wd4996` disables the C4996 diagnostic. Revisit if a future
// Electron actually removes the overload (then native-keymap needs a source fix).
const NATIVE_KEYMAP_DEPRECATION_REPLACEMENT: [string, string] = [
	"'/ZH:SHA_256'",
	"'/ZH:SHA_256', '/wd4996'",
];

// Disables the Spectre-mitigation requirement (MSB8040). Applied to every .gyp
// in the bun store that sets it. These addons don't depend on Spectre hardening.
const SPECTRE_REPLACEMENT: [string, string] = [
	"'SpectreMitigation': 'Spectre'",
	"'SpectreMitigation': 'false'",
];

// node-pty winpty.gyp-only: removes the two space-sensitive `cmd /c` actions.
const WINPTY_GYP_ACTION_REPLACEMENTS: Array<[string, string]> = [
	[
		"'WINPTY_COMMIT_HASH%': '<!(cmd /c \"cd shared && GetCommitHash.bat\")',",
		"'WINPTY_COMMIT_HASH%': 'none',",
	],
	[
		"'<!(cmd /c \"cd shared && UpdateGenVersion.bat <(WINPTY_COMMIT_HASH)\")',",
		"'gen',",
	],
];

function findNodePtyDirs(repoRoot: string): string[] {
	const pattern = join(
		repoRoot,
		"node_modules",
		".bun",
		"node-pty@*",
		"node_modules",
		"node-pty",
	);
	try {
		return globSync(pattern);
	} catch {
		return [];
	}
}

function findNativeKeymapDirs(repoRoot: string): string[] {
	const pattern = join(
		repoRoot,
		"node_modules",
		".bun",
		"native-keymap@*",
		"node_modules",
		"native-keymap",
	);
	try {
		return globSync(pattern);
	} catch {
		return [];
	}
}

function applyReplacements(
	filePath: string,
	replacements: Array<[string, string]>,
): boolean {
	if (!existsSync(filePath)) return false;
	let src = readFileSync(filePath, "utf8");
	let changed = false;
	for (const [from, to] of replacements) {
		if (src.includes(from)) {
			// replaceAll, not replace: the same string can appear on multiple
			// targets (e.g. SpectreMitigation is set on every winpty.gyp target).
			src = src.replaceAll(from, to);
			changed = true;
		}
	}
	if (changed) writeFileSync(filePath, src);
	return changed;
}

function ensureGenVersionHeader(nodePtyDir: string): boolean {
	const genDir = join(nodePtyDir, "deps", "winpty", "src", "gen");
	const headerPath = join(genDir, "GenVersion.h");
	if (existsSync(headerPath)) return false;

	let version = "0.0.0-unknown";
	const versionPath = join(nodePtyDir, "deps", "winpty", "VERSION.txt");
	if (existsSync(versionPath))
		version = readFileSync(versionPath, "utf8").trim();

	mkdirSync(genDir, { recursive: true });
	writeFileSync(
		headerPath,
		`// AUTO-GENERATED by superset patch-native-builds.ts (spaces-in-path workaround)\n` +
			`const char GenVersion_Version[] = "${version}";\n` +
			`const char GenVersion_Commit[] = "none";\n`,
	);
	return true;
}

/** node-pty-specific: remove the winpty `cmd /c` gyp actions + gen the header. */
function patchNodePtyWinpty(dirs: string[], details: string[]): void {
	for (const dir of dirs) {
		const changed: string[] = [];
		const winptyGyp = join(dir, "deps", "winpty", "src", "winpty.gyp");
		if (applyReplacements(winptyGyp, WINPTY_GYP_ACTION_REPLACEMENTS)) {
			changed.push("winpty.gyp cmd-actions removed");
		}
		if (ensureGenVersionHeader(dir)) changed.push("GenVersion.h created");
		if (changed.length > 0) details.push(`${dir}: ${changed.join("; ")}`);
	}
}

/**
 * General Spectre-mitigation disable: scan every `.gyp` under the bun store and
 * turn off `SpectreMitigation: 'Spectre'`. Catches node-pty, native-keymap, and
 * any future compiling addon without per-module patching.
 */
function disableSpectreMitigation(repoRoot: string, details: string[]): number {
	const pattern = join(
		repoRoot,
		"node_modules",
		".bun",
		"**",
		"node_modules",
		"**",
		"*.gyp",
	);
	let gypFiles: string[];
	try {
		gypFiles = globSync(pattern);
	} catch {
		return 0;
	}
	let files = 0;
	for (const gyp of gypFiles) {
		if (applyReplacements(gyp, [SPECTRE_REPLACEMENT])) files++;
	}
	if (files > 0)
		details.push(`Spectre mitigation disabled in ${files} .gyp file(s)`);
	return files;
}

export function patchNativeBuildsForWindows(repoRoot: string): {
	details: string[];
} {
	const details: string[] = [];
	if (process.platform !== "win32") return { details };
	// node-pty-specific cmd-action/header patch first, then the general Spectre
	// sweep (which also covers node-pty's own Spectre targets).
	patchNodePtyWinpty(findNodePtyDirs(repoRoot), details);
	disableSpectreMitigation(repoRoot, details);
	// native-keymap: suppress the V8-API deprecation (C4996) so it compiles
	// against Electron 40's V8. See the replacement's doc comment.
	for (const dir of findNativeKeymapDirs(repoRoot)) {
		if (
			applyReplacements(join(dir, "binding.gyp"), [
				NATIVE_KEYMAP_DEPRECATION_REPLACEMENT,
			])
		) {
			details.push(`${dir}: V8-deprecation C4996 suppressed (/wd4996)`);
		}
	}
	return { details };
}

// CLI entry: `bun run scripts/patch-native-builds.ts` — patches in place and reports.
// Use `import.meta.main` (Bun) plus a path-tail fallback; the naive
// `import.meta.url === file://\${argv[1]}` check breaks on Windows / spaced paths
// (import.meta.url URL-encodes the space to %20, argv[1] does not).
const argv1 = process.argv[1]?.replace(/\\/g, "/");
const isMain =
	import.meta.main === true || argv1?.endsWith("patch-native-builds.ts");
if (isMain) {
	const result = patchNativeBuildsForWindows(process.cwd());
	if (result.details.length === 0) {
		console.log(
			"[patch-native-builds] nothing to patch (non-win32, no native gyp files, or already patched)",
		);
	} else {
		console.log("[patch-native-builds] patched:");
		for (const d of result.details) console.log(`  ${d}`);
	}
}
